In [4]:
import numpy as np

In [7]:
x = np.array([1, 2, 3, 4, 5])

print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
print(x.shape)

(5,)


In [9]:
x = x.reshape(5, 1)

print(x)
print(x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [10]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

y = np.array([0, 1, 0, 1])

In [11]:
print("X:")
print(X)

print("\ny:")
print(y)

X:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

y:
[0 1 0 1]


In [16]:
print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (4, 2)
y Shape: (4,)


In [18]:
print(X[0])
print(X[0][1])
print(y[2])

[1 2]
2
0


In [19]:
X = np.array([
    [180, 80, 40],
    [170, 90, 30],
    [160, 90, 50]
])

y = np.array([1, 0, 1])

In [21]:
print("X:")
print(X)

print("\ny:")
print(y)

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)

X:
[[180  80  40]
 [170  90  30]
 [160  90  50]]

y:
[1 0 1]

X Shape: (3, 3)
y Shape: (3,)


In [23]:
print(X[1])
print(X[2][0])

[170  90  30]
160


In [24]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [25]:
print("Shape:", arr.shape)

Shape: (6,)


In [27]:
arr = arr.reshape(2, 3)

print(arr)
print(arr.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [28]:
print(arr[0])

[10 20 30]


In [29]:
print(arr[:, 1])

[20 50]
