# Arrays
Creating a basic NumPy array.

In [51]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


# Shape
Checking the dimensions of the array.

In [52]:
a.shape

(3,)

# Indexing
Accessing specific elements from the array.

In [53]:
print(a[0])
print(a[1:3])

1
[2 3]


# Reshaping
Changing array shap into matrix form.

In [54]:
a = np.array([1, 2, 3, 4])
a.reshape(2, 2)

array([[1, 2],
       [3, 4]])

# Math Operations
Performing mathematical operations on arrays.

In [55]:
a = np.array([1, 2, 3])

print(a + 10)
print(a * 2)
print(np.mean(a))
print(np.sum(a))

[11 12 13]
[2 4 6]
2.0
6


# Task 1: Matrix Creation

In [56]:
print(np.zeros((3,3)))
print(np.ones((2,2)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Task 2: Random Arrays

In [57]:
print(np.random.rand(3,3))
print(np.random.randint(1, 10, (2,2)))

[[0.59882906 0.50801664 0.30844723]
 [0.00469323 0.24039624 0.45917211]
 [0.92190053 0.57597888 0.75208599]]
[[1 3]
 [5 8]]


# Task 3: Array Math

In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(np.dot(a,b))

[5 7 9]
[ 4 10 18]
32


# Task 4: Reshape + Index

In [59]:
a = np.arange(9)

b = a.reshape(3,3)

print(b)
print(a[0])
print(a[0:5])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
[0 1 2 3 4]


# MINI CHALLENGE

In [60]:
import numpy as np

a = np.random.randint(1, 100, (3,3))

print("Matrix: ")
print(a)

print("\nSum: ")
print(np.sum(a))

print("\nMean: ")
print(np.mean(a))

print("\nTranspose: ")
print(a.T)

print("\nMax Values: " )
print(np.max(a))

Matrix: 
[[16 70 37]
 [63 86 42]
 [81 65 37]]

Sum: 
497

Mean: 
55.22222222222222

Transpose: 
[[16 63 81]
 [70 86 65]
 [37 42 37]]

Max Values: 
86


# Summary

Today I learned NumPy basics:

- Creating arrays using `np.array()`
- Checking shape using `.shape`
- Indexing and slicing arrays
- Reshaping arrays using `.reshape()`
- Performing mathematical operations
- Creating zero, one, and identity matrices
- Generating random arrays
- Array addition, multiplication, and dot product
- Finding sum, mean, transpose, and max value

This was my first hands-on practice with NumPy arrays and matrix operations.